import { Exam, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cranio', name: 'Crânio', icon: 'Brain' },
  { id: 'coluna', name: 'Coluna', icon: 'PersonStanding' },
  { id: 'torax', name: 'Tórax', icon: 'Stethoscope' },
  { id: 'abdome', name: 'Abdome', icon: 'Activity' },
  { id: 'pelve', name: 'Pelve', icon: 'Disc' },
  { id: 'membros-superiores', name: 'Membros Superiores', icon: 'Hand' },
  { id: 'membros-inferiores', name: 'Membros Inferiores', icon: 'Footprints' },
  { id: 'pediatria', name: 'Pediatria (Infantil)', icon: 'Baby' },
];

export const INITIAL_EXAMS: Exam[] = [
  // Abdome
  {
    id: 'a1',
    name: 'ABDOME',
    category: 'abdome',
    positioning: 'Paciente em decúbito dorsal.',
    incidences: 'AP em decúbito dorsal',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Alinhar com a crista ilíaca.',
    structures: 'Órgãos abdominais, psoas.',
    type: 'rotina',
  },
  {
    id: 'a2',
    name: 'ABDOME AGUDO',
    category: 'abdome',
    positioning: 'Rotina completa para avaliação de abdome agudo.',
    incidences: 'PA de tórax; AP em decúbito dorsal; AP em ortostase',
    angulation: 'Perpendicular.',
    ffd: '100 cm (Tórax 180cm)',
    kv: '75-85',
    mas: '30-60',
    observations: 'Verificar níveis hidroaéreos e pneumoperitônio.',
    structures: 'Abdome total e diafragma.',
    type: 'rotina',
  },
  // Membros Superiores
  {
    id: 'ms1',
    name: 'ANTEBRAÇO',
    category: 'membros-superiores',
    positioning: 'AP: Braço estendido, palma para cima. Perfil: Cotovelo fletido 90 graus.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Incluir rádio e ulna por inteiro.',
    structures: 'Rádio, ulna, carpo proximal.',
    type: 'rotina',
  },
  {
    id: 'ms2',
    name: 'CLAVÍCULA',
    category: 'membros-superiores',
    positioning: 'AP e Axial com o paciente em ortostase ou decúbito.',
    incidences: 'AP; Axial',
    angulation: 'Axial: 15-30 graus cefálico.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Suspensão de respiração.',
    structures: 'Clavícula por inteiro.',
    type: 'rotina',
  },
  {
    id: 'ms3',
    name: 'COTOVELO',
    category: 'membros-superiores',
    positioning: 'AP: Braço estendido. Perfil: Cotovelo fletido 90 graus.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '5-10',
    observations: 'Visualizar articulação do cotovelo.',
    structures: 'Úmero distal, rádio e ulna proximais.',
    type: 'rotina',
  },
  {
    id: 'ms4',
    name: 'DEDOS (QD)',
    category: 'membros-superiores',
    positioning: 'PA e Oblíqua da mão/dedos.',
    incidences: 'PA; Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-4',
    observations: 'Isolar o dedo de interesse na oblíqua.',
    structures: 'Falanges e articulações.',
    type: 'rotina',
  },
  {
    id: 'ms5',
    name: 'ESCÁPULA',
    category: 'membros-superiores',
    positioning: 'AP e Perfil escapular (Y).',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Abduzir o braço no AP para liberar a escápula.',
    structures: 'Corpo da escápula, acrômio.',
    type: 'rotina',
  },
  {
    id: 'ms6',
    name: 'MÃO',
    category: 'membros-superiores',
    positioning: 'PA: Mão espalmada. Oblíqua: Mão rodada 45 graus.',
    incidences: 'PA; Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-5',
    observations: 'Dedos afastados na oblíqua.',
    structures: 'Metacarpos, falanges.',
    type: 'rotina',
  },
  {
    id: 'ms7',
    name: 'OMBRO SEM TRAUMA',
    category: 'membros-superiores',
    positioning: 'Paciente em ortostase ou decúbito dorsal.',
    incidences: 'AP rotação interna; AP rotação externa',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-35',
    observations: 'Avaliar os tubérculos maior e menor.',
    structures: 'Articulação glenoumeral.',
    type: 'rotina',
  },
  {
    id: 'ms8',
    name: 'OMBRO COM TRAUMA',
    category: 'membros-superiores',
    positioning: 'Evitar movimentação excessiva do braço.',
    incidences: 'AP neutro; Perfil axilar; Perfil escapular',
    angulation: 'Axilar: 15-30 graus medial.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Perfil escapular é para luxações.',
    structures: 'Ombro e escápula.',
    type: 'rotina',
  },
  {
    id: 'ms9',
    name: 'PUNHO',
    category: 'membros-superiores',
    positioning: 'PA: Mão espalmada. Perfil: Mão e antebraço em lateral.',
    incidences: 'PA; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '3-6',
    observations: 'Centralizar no carpo.',
    structures: 'Ossos do carpo, rádio e ulna distais.',
    type: 'rotina',
  },
  {
    id: 'ms10',
    name: 'ÚMERO',
    category: 'membros-superiores',
    positioning: 'AP e Transtorácico (se necessário).',
    incidences: 'AP rotação interna/externa; Transtorácico',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Incluir as duas articulações.',
    structures: 'Corpo do úmero.',
    type: 'rotina',
  },
  // Tórax
  {
    id: 't1',
    name: 'ARCOS COSTAIS',
    category: 'torax',
    positioning: 'Oblíqua anterior ou posterior conforme área de interesse.',
    incidences: 'Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '20-40',
    observations: 'Apneia em inspiração.',
    structures: 'Arcos costais.',
    type: 'rotina',
  },
  {
    id: 't2',
    name: 'ESTERNO',
    category: 'torax',
    positioning: 'OAD: Paciente rodado 15-20 graus. Perfil: Braços para trás.',
    incidences: 'OAD; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '30-50',
    observations: 'OAD projeta o esterno sobre o coração.',
    structures: 'Esterno.',
    type: 'rotina',
  },
  {
    id: 't3',
    name: 'TÓRAX ADULTO',
    category: 'torax',
    positioning: 'Ortostase, tórax contra o bucky.',
    incidences: 'PA; Perfil',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '110-120',
    mas: '2-5',
    observations: 'Inspiração profunda mantida.',
    structures: 'Pulmões, silhueta cardíaca.',
    type: 'rotina',
  },
  // Crânio & Face
  {
    id: 'c1',
    name: 'ARCO ZIGOMÁTICO',
    category: 'cranio',
    positioning: 'Towne: AP Axial. Tangencial: Cabeça inclinada.',
    incidences: 'Towne; Tangencial',
    angulation: 'Towne: 30-37 graus caudal.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '15-25',
    observations: 'Técnica fina para arcos zigomáticos.',
    structures: 'Arcos zigomáticos.',
    type: 'especial',
  },
  {
    id: 'c2',
    name: 'ATM',
    category: 'cranio',
    positioning: 'Método Law: Lateral com boca aberta e fechada.',
    incidences: 'Método Law (boca aberta e fechada)',
    angulation: '15 graus caudal.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-30',
    observations: 'Avaliar excursão condilar.',
    structures: 'Articulação Temporomandibular.',
    type: 'especial',
  },
  {
    id: 'c3',
    name: 'CAVUM',
    category: 'cranio',
    positioning: 'Perfil de face com técnica de partes moles.',
    incidences: 'Perfil de face (boca aberta/fechada)',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-10',
    observations: 'Visualizar adenoide.',
    structures: 'Nasofaringe.',
    type: 'rotina',
  },
  {
    id: 'c4',
    name: 'CRÂNIO',
    category: 'cranio',
    positioning: 'Towne, PA de Crânio e Perfil.',
    incidences: 'Towne; PA; Perfil',
    angulation: 'Towne: 30 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Evitar rotação.',
    structures: 'Calota craniana.',
    type: 'rotina',
  },
  {
    id: 'c5',
    name: 'MANDÍBULA',
    category: 'cranio',
    positioning: 'PA de mandíbula e Oblíquas axiolaterais.',
    incidences: 'PA; Bellot (axiolateral)',
    angulation: 'Bellot: 25-30 graus cefálico.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-35',
    observations: 'Avaliar corpo e ramos.',
    structures: 'Mandíbula.',
    type: 'rotina',
  },
  {
    id: 'c6',
    name: 'MASTOIDE',
    category: 'cranio',
    positioning: 'Método Law ou Schuller.',
    incidences: 'Law',
    angulation: '15 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-50',
    observations: 'Visualizar células da mastoide.',
    structures: 'Mastoides.',
    type: 'especial',
  },
  {
    id: 'c7',
    name: 'NARIZ',
    category: 'cranio',
    positioning: 'Perfil direito e esquerdo.',
    incidences: 'Perfil D/E',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Técnica de partes moles.',
    structures: 'Ossos nasais.',
    type: 'rotina',
  },
  {
    id: 'c8',
    name: 'ÓRBITA',
    category: 'cranio',
    positioning: 'Waters e Rhese (canal óptico).',
    incidences: 'Mento-naso; Rhese',
    angulation: 'Rhese: Cabeça rodada 37 graus.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Visualizar soalho das órbitas.',
    structures: 'Órbitas.',
    type: 'especial',
  },
  {
    id: 'c9',
    name: 'SEIOS DA FACE',
    category: 'cranio',
    positioning: 'Caldwell e Waters.',
    incidences: 'Fronto-naso; Mento-naso',
    angulation: 'Variável.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-45',
    observations: 'Waters com boca aberta se possível.',
    structures: 'Seios paranasais.',
    type: 'rotina',
  },
  {
    id: 'c10',
    name: 'SELA TÚRCICA',
    category: 'cranio',
    positioning: 'Towne e Perfil preciso.',
    incidences: 'Towne; Perfil',
    angulation: 'Towne: 30 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Sela túrcica centralizada.',
    structures: 'Sela túrcica.',
    type: 'especial',
  },
  // Coluna
  {
    id: 'col1',
    name: 'COLUMNA CERVICAL',
    category: 'coluna',
    positioning: 'AP axial e Perfil verdadeiro.',
    incidences: 'AP axial; Perfil',
    angulation: 'AP: 15-20 graus cefálico.',
    ffd: '100 cm (PF 150-180cm)',
    kv: '70-80',
    mas: '15-30',
    observations: 'Ombros para baixo no perfil.',
    structures: 'C1 a C7.',
    type: 'rotina',
  },
  {
    id: 'col2',
    name: 'COLUMNA TORÁCICA',
    category: 'coluna',
    positioning: 'AP e Perfil em decúbito ou orto.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Técnica de respiração no perfil.',
    structures: 'Vértebras torácicas.',
    type: 'rotina',
  },
  {
    id: 'col3',
    name: 'COLUMNA LOMBAR',
    category: 'coluna',
    positioning: 'AP e Perfil.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-95',
    mas: '60-120',
    observations: 'Fletir joelhos no AP.',
    structures: 'L1 a L5.',
    type: 'rotina',
  },
  {
    id: 'col4',
    name: 'SACRO/COCCIX',
    category: 'coluna',
    positioning: 'AP Axial e Perfil.',
    incidences: 'AP axial; Perfil',
    angulation: 'Sacro AP: 15º cefálico; Cóccix: 10º caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-50',
    observations: 'Esvaziar bexiga antes.',
    structures: 'Sacro e cóccix.',
    type: 'rotina',
  },
  // Pelve
  {
    id: 'p1',
    name: 'BACIA',
    category: 'pelve',
    positioning: 'AP e Cleaves.',
    incidences: 'AP; Posição de rã',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Pés em rotação interna no AP.',
    structures: 'Pelve e quadris.',
    type: 'rotina',
  },
  // Membros Inferiores
  {
    id: 'mi1',
    name: 'CALCÂNEO',
    category: 'membros-inferiores',
    positioning: 'Axial de calcâneo e perfil lateral.',
    incidences: 'Axial; Perfil',
    angulation: 'Axial: 40 graus cefálico.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '10-20',
    observations: 'Dorsoflexão máxima no axial.',
    structures: 'Totalidade do calcâneo.',
    type: 'rotina',
  },
  {
    id: 'mi2',
    name: 'DEDOS (PD)',
    category: 'membros-inferiores',
    positioning: 'AP e Oblíqua dos artelhos.',
    incidences: 'AP; Oblíqua',
    angulation: '10-15 graus cefálico.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Isolar o artelho de interesse.',
    structures: 'Falanges do pé.',
    type: 'rotina',
  },
  {
    id: 'mi3',
    name: 'FÊMUR DISTAL',
    category: 'membros-inferiores',
    positioning: 'AP e Perfil focados no joelho/fêmur distal.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Incluir articulação do joelho.',
    structures: 'Fêmur distal.',
    type: 'rotina',
  },
  {
    id: 'mi4',
    name: 'FÊMUR PROXIMAL',
    category: 'membros-inferiores',
    positioning: 'AP de quadril/fêmur proximal.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Incluir articulação coxofemoral.',
    structures: 'Fêmur proximal.',
    type: 'rotina',
  },
  {
    id: 'mi5',
    name: 'FOSSA INTERCONDILAR',
    category: 'membros-inferiores',
    positioning: 'Método de Túnel: PA ou AP com joelho fletido.',
    incidences: 'PA (método de túnel)',
    angulation: '40-45 graus caudal.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Visualizar eminência intercondilar.',
    structures: 'Fossa intercondilar.',
    type: 'especial',
  },
  {
    id: 'mi6',
    name: 'JOELHO',
    category: 'membros-inferiores',
    positioning: 'AP e Perfil fletido 20-30 graus.',
    incidences: 'AP; Perfil',
    angulation: '5-7 graus cefálico.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Carga se solicitada.',
    structures: 'Joelho.',
    type: 'rotina',
  },
  {
    id: 'mi7',
    name: 'PATELA',
    category: 'membros-inferiores',
    positioning: 'Tangencial (Settegast) e Perfil verdadeiro.',
    incidences: 'Tangencial; Perfil',
    angulation: 'Tangencial: 15-20 graus.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-12',
    observations: 'Cuidado ao fletir joelho em trauma.',
    structures: 'Patela e espaço patelofemoral.',
    type: 'rotina',
  },
  {
    id: 'mi8',
    name: 'PÉ',
    category: 'membros-inferiores',
    positioning: 'AP com 10º de inclinação e Oblíqua medial.',
    incidences: 'AP; Oblíqua',
    angulation: '10 graus cefálico.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Carga se necessário.',
    structures: 'Tarsos, metatarsos e falanges.',
    type: 'rotina',
  },
  {
    id: 'mi9',
    name: 'PERNA',
    category: 'membros-inferiores',
    positioning: 'AP e Perfil de tíbia e fíbula.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Incluir joelho e tornozelo.',
    structures: 'Tíbia e fíbula.',
    type: 'rotina',
  },
  {
    id: 'mi10',
    name: 'SESAMOIDE',
    category: 'membros-inferiores',
    positioning: 'Tangencial de Lewis: Pé em hiperextensão.',
    incidences: 'Tangencial (Lewis)',
    angulation: 'Perpendicular ao detector.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '3-6',
    observations: 'Puxar os dedos com fita.',
    structures: 'Ossos sesamoides do hálux.',
    type: 'especial',
  },
  {
    id: 'mi11',
    name: 'TORNOZELO',
    category: 'membros-inferiores',
    positioning: 'AP e Perfil lateral.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '5-12',
    observations: 'Pé em 90 graus.',
    structures: 'Maleólos e tálus.',
    type: 'rotina',
  },
  // Pediatria
  {
    id: 'ped1',
    name: 'TÓRAX PEDIÁTRICO',
    category: 'pediatria',
    positioning: 'Geralmente AP em decúbito ou ortostase imobilizado.',
    incidences: 'AP; Perfil',
    angulation: 'Perpendicular.',
    ffd: '100-150 cm',
    kv: '55-65',
    mas: '1.5-4',
    observations: 'Exposição rápida.',
    structures: 'Campos pulmonares.',
    type: 'rotina',
  },
];

