import { Exam, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cranio', name: 'Crânio', icon: 'Brain' },
  { id: 'coluna', name: 'Coluna', icon: 'PersonStanding' },
  { id: 'torax', name: 'Tórax', icon: 'Stethoscope' },
  { id: 'abdome', name: 'Abdome', icon: 'Activity' },
  { id: 'pelve', name: 'Pelve', icon: 'Disc' },
  { id: 'membros-superiores', name: 'Membros Superiores', icon: 'Hand' },
  { id: 'membros-inferiores', name: 'Membros Inferiores', icon: 'Footprints' },
  { id: 'pediatria', name: 'Pediatria (Infantil)', icon: 'Baby' },
];

export const INITIAL_EXAMS: Exam[] = [
  // Crânio & Face
  {
    id: 'c1',
    name: 'Crânio AP e LAT',
    category: 'cranio',
    positioning: 'AP: Paciente em decúbito dorsal ou ortostase, LOM perpendicular ao receptor. LAT: Paciente em perfil verdadeiro, plano sagital mediano paralelo ao receptor.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-30',
    observations: 'Verificar alinhamento para evitar rotação.',
    structures: 'Ossos frontais, parietais, base do crânio.',
    type: 'rotina',
  },
  {
    id: 'c2',
    name: 'SAF (Seios da Face)',
    category: 'cranio',
    positioning: 'Waters (Mento-naso) e Caldwell (Fronto-naso).',
    incidences: 'Waters, Caldwell, Perfil',
    angulation: 'Variável conforme incidência.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-40',
    observations: 'Waters: Boca aberta para seio esfenoidal.',
    structures: 'Seios maxilares, frontais e etmoidais.',
    type: 'rotina',
  },
  {
    id: 'c3',
    name: 'Cavum',
    category: 'cranio',
    positioning: 'Paciente em perfil verdadeiro, queixo levemente elevado, respiração nasal.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-10',
    observations: 'Técnica de partes moles para visualizar adenoides.',
    structures: 'Nasofaringe, adenoides.',
    type: 'especial',
  },
  {
    id: 'c4',
    name: 'Ossos do Nariz',
    category: 'cranio',
    positioning: 'Perfil direito e esquerdo, plano sagital mediano paralelo ao filme.',
    incidences: 'Perfil (LAT)',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Técnica fina para ossos pequenos.',
    structures: 'Ossos nasais e espinha nasal.',
    type: 'rotina',
  },
  // Coluna
  {
    id: 'col1',
    name: 'Cervical AP 15/20º',
    category: 'coluna',
    positioning: 'Paciente em ortostase ou decúbito, queixo elevado.',
    incidences: 'AP',
    angulation: '15-20 graus cranial.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Visualizar de C3 a T2.',
    structures: 'Corpos vertebrais cervicais.',
    type: 'rotina',
  },
  {
    id: 'col2',
    name: 'Cervical LAT',
    category: 'coluna',
    positioning: 'Paciente em perfil verdadeiro, ombros relaxados (puxar para baixo).',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '150-180 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'DFF maior para reduzir magnificação.',
    structures: 'C1 a C7, espaços intervertebrais.',
    type: 'rotina',
  },
  {
    id: 'col3',
    name: 'C. Torácica AP',
    category: 'coluna',
    positioning: 'Paciente em decúbito dorsal, braços ao lado do corpo.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-50',
    observations: 'Usar efeito anódico (parte mais grossa sob o cátodo).',
    structures: 'Vértebras torácicas T1 a T12.',
    type: 'rotina',
  },
  {
    id: 'col4',
    name: 'C. Torácica LAT',
    category: 'coluna',
    positioning: 'Paciente em perfil, braços elevados à frente.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-90',
    mas: '40-80',
    observations: 'Respiração suave ou apneia em expiração.',
    structures: 'Corpos vertebrais e espaços discais em perfil.',
    type: 'rotina',
  },
  {
    id: 'col5',
    name: 'C. Lombar AP',
    category: 'coluna',
    positioning: 'Paciente em decúbito dorsal, joelhos fletidos para reduzir lordose.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Alinhar com a crista ilíaca (L4).',
    structures: 'L1 a L5, sacro.',
    type: 'rotina',
  },
  {
    id: 'col6',
    name: 'C. Lombar LAT',
    category: 'coluna',
    positioning: 'Paciente em perfil, joelhos fletidos para estabilidade.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '85-95',
    mas: '60-120',
    observations: 'Pode necessitar angulação de 5-8 graus caudal se cintura for larga.',
    structures: 'Corpos vertebrais de perfil, articulações intervertebrais.',
    type: 'rotina',
  },
  // Tórax
  {
    id: 't1',
    name: 'Tórax PA',
    category: 'torax',
    positioning: 'Ortostase, tórax contra o bucky, braços rodados à frente.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '110-120',
    mas: '2-5',
    observations: 'Grande inspiração mantida.',
    structures: 'Pulmões, silhueta cardíaca.',
    type: 'rotina',
  },
  {
    id: 't2',
    name: 'Tórax LAT',
    category: 'torax',
    positioning: 'Ortostase, lateral esquerda contra o bucky, braços elevados.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '120-130',
    mas: '5-10',
    observations: 'Avaliar espaço retroesternal.',
    structures: 'Pulmões em perfil.',
    type: 'rotina',
  },
  {
    id: 't3',
    name: 'Costelas',
    category: 'torax',
    positioning: 'AP ou PA e Oblíquas, dependendo da área de dor.',
    incidences: 'AP/PA e Oblíquo',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '20-40',
    observations: 'Apneia em inspiração para costelas superiores, expiração para inferiores.',
    structures: 'Arcos costais.',
    type: 'rotina',
  },
  // Abdome
  {
    id: 'a1',
    name: 'Abdome AP Orto',
    category: 'abdome',
    positioning: 'Paciente em pé (ortostase), costas contra o bucky.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Visualizar níveis hidroaéreos e ar livre sob diafragma.',
    structures: 'Alças intestinais, fígado, baço.',
    type: 'rotina',
  },
  {
    id: 'a2',
    name: 'Abdome AP Dec',
    category: 'abdome',
    positioning: 'Paciente em decúbito dorsal (deitado).',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Rotina de abdome agudo.',
    structures: 'Órgãos abdominais, psoas.',
    type: 'rotina',
  },
  // Membros Superiores
  {
    id: 'ms1',
    name: 'Ombro AP / Clavícula',
    category: 'membros-superiores',
    positioning: 'AP de ombro em rotação neutra; clavícula em AP e AP Axial.',
    incidences: 'AP, Axial',
    angulation: 'Clavícula Axial: 15-30 graus cefálico.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Suspensão de respiração.',
    structures: 'Úmero proximal, clavícula, escápula.',
    type: 'rotina',
  },
  {
    id: 'ms2',
    name: 'Ombro Perfil (Escapular Y)',
    category: 'membros-superiores',
    positioning: 'Paciente rodado 45-60 graus para o lado afetado.',
    incidences: 'Perfil Transescapular',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Útil para luxações.',
    structures: 'Escápula, acrômio, processo coracoide.',
    type: 'especial',
  },
  {
    id: 'ms3',
    name: 'Úmero AP',
    category: 'membros-superiores',
    positioning: 'Paciente em decúbito ou ortostase, braço estendido e supinado.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '8-15',
    observations: 'Incluir articulações do ombro e cotovelo.',
    structures: 'Corpo do úmero.',
    type: 'rotina',
  },
  {
    id: 'ms4',
    name: 'Úmero Perfil',
    category: 'membros-superiores',
    positioning: 'Braço fletido 90 graus, face medial contra o filme.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Perfil verdadeiro do úmero.',
    structures: 'Úmero lateral.',
    type: 'rotina',
  },
  {
    id: 'ms5',
    name: 'Antebraço AP e Perfil',
    category: 'membros-superiores',
    positioning: 'AP: Braço estendido, palma para cima. Perfil: Cotovelo fletido 90 graus.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Incluir rádio e ulna por inteiro.',
    structures: 'Rádio, ulna, carpo proximal.',
    type: 'rotina',
  },
  {
    id: 'ms6',
    name: 'Punho PA e Perfil',
    category: 'membros-superiores',
    positioning: 'PA: Mão espalmada. Perfil: Mão e antebraço em lateral.',
    incidences: 'PA e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '3-6',
    observations: 'Centralizar no carpo.',
    structures: 'Ossos do carpo, rádio e ulna distais.',
    type: 'rotina',
  },
  {
    id: 'ms7',
    name: 'Mão PA e Oblíqua',
    category: 'membros-superiores',
    positioning: 'PA: Mão espalmada. Oblíqua: Mão rodada 45 graus.',
    incidences: 'PA e Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-5',
    observations: 'Dedos afastados na oblíqua.',
    structures: 'Metacarpos, falanges.',
    type: 'rotina',
  },
  // Pelve
  {
    id: 'p1',
    name: 'Pelve AP e RA (Rã)',
    category: 'pelve',
    positioning: 'AP: Pernas rodadas 15-20 graus para dentro. RA (Cleaves): Pernas fletidas e abduzidas.',
    incidences: 'AP e Cleaves (Rã)',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'RA é útil para articulações coxofemorais.',
    structures: 'Quadril, sínfise púbica, ílio.',
    type: 'rotina',
  },
  // Membros Inferiores
  {
    id: 'mi1',
    name: 'Fêmur AP e Perfil',
    category: 'membros-inferiores',
    positioning: 'AP: Perna em extensão, rotação interna. Perfil: Lateral com outra perna afastada.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Pode requerer dois filmes para incluir quadril e joelho.',
    structures: 'Corpo do fêmur.',
    type: 'rotina',
  },
  {
    id: 'mi2',
    name: 'Joelho AP/PF 5º a 7º',
    category: 'membros-inferiores',
    positioning: 'AP: Extensão total. Perfil: Fletido 20-30 graus.',
    incidences: 'AP e Perfil',
    angulation: 'AP: 5-7 graus cefálico (em pacientes maiores).',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Carga pode ser solicitada.',
    structures: 'Fêmur distal, tíbia proximal, patela.',
    type: 'rotina',
  },
  {
    id: 'mi3',
    name: 'Perna AP e PF',
    category: 'membros-inferiores',
    positioning: 'AP: Dorsoflexão do pé. Perfil: Rodar perna para lateral.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '6-12',
    observations: 'Incluir joelho e tornozelo.',
    structures: 'Tíbia e fíbula.',
    type: 'rotina',
  },
  {
    id: 'mi4',
    name: 'Tornozelo AP e PF',
    category: 'membros-inferiores',
    positioning: 'AP: Pé em 90 graus. Perfil: Lateral verdadeira.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-10',
    observations: 'Avaliar encaixe do tálus.',
    structures: 'Maléolos, tálus.',
    type: 'rotina',
  },
  {
    id: 'mi5',
    name: 'Calcâneo Axial 40º',
    category: 'membros-inferiores',
    positioning: 'Paciente sentado, perna estendida, puxar o pé com fita.',
    incidences: 'Planto-dorsal Axial',
    angulation: '40 graus cefálico (em relação ao eixo do pé).',
    ffd: '100 cm',
    kv: '60-70',
    mas: '10-20',
    observations: 'Dorsoflexão máxima.',
    structures: 'Totalidade do calcâneo.',
    type: 'especial',
  },
  {
    id: 'mi6',
    name: 'Pé AP 10º e Oblíqua',
    category: 'membros-inferiores',
    positioning: 'AP: Pé sobre o filme. Oblíqua: Rodar pé 30 graus medialmente.',
    incidences: 'AP e Oblíqua',
    angulation: 'AP: 10 graus em direção ao calcâneo.',
    ffd: '100 cm',
    kv: '55-60',
    mas: '3-6',
    observations: 'Carga opcional.',
    structures: 'Metatarsos, tarsos, falanges.',
    type: 'rotina',
  },
  // Pediatria / Infantil
  {
    id: 'ped1',
    name: 'Tórax Infantil (BB)',
    category: 'pediatria',
    positioning: 'Paciente no Pigg-O-Stat ou imobilizado manualmente pelos pais.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100-150 cm',
    kv: '55-65',
    mas: '1-3',
    observations: 'Exposição rápida para evitar movimento.',
    structures: 'Campos pulmonares pediátricos.',
    type: 'rotina',
  },
  {
    id: 'ped2',
    name: 'Abdome Infantil',
    category: 'pediatria',
    positioning: 'Decúbito dorsal, braços para cima.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '2-5',
    observations: 'Baixa dose necessária.',
    structures: 'Abdome pediátrico.',
    type: 'rotina',
  },
  {
    id: 'ped3',
    name: 'Crânio Infantil',
    category: 'pediatria',
    positioning: 'Geralmente em decúbito com imobilização.',
    incidences: 'AP e Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '5-15',
    observations: 'Verificar fontanelas se necessário.',
    structures: 'Crânio pediátrico.',
    type: 'rotina',
  },
  {
    id: 'ped4',
    name: 'SAF Infantil',
    category: 'pediatria',
    positioning: 'Igual ao adulto, mas adaptado à cooperação da criança.',
    incidences: 'Waters e Caldwell',
    angulation: 'Variável.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Seios podem não estar totalmente desenvolvidos.',
    structures: 'Seios da face pediátricos.',
    type: 'rotina',
  },
  {
    id: 'ped5',
    name: 'Pelve Infantil',
    category: 'pediatria',
    positioning: 'Decúbito dorsal, evitar rotação.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-15',
    observations: 'Triagem de displasia de quadril.',
    structures: 'Articulações coxo-femorais e pelve.',
    type: 'rotina',
  },
  {
    id: 'ped6',
    name: 'Clavícula Infantil',
    category: 'pediatria',
    positioning: 'AP, imobilizar os braços se necessário.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '2-4',
    observations: 'Frequente em traumas de parto.',
    structures: 'Clavícula pediátrica.',
    type: 'rotina',
  },
  {
    id: 'ped7',
    name: 'Ossos Longos (Escaniometria)',
    category: 'pediatria',
    positioning: 'Paciente imobilizado, régua escanométrica ao lado.',
    incidences: 'AP de MMII',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Medição de discrepância de membros.',
    structures: 'Fêmur e Tíbia.',
    type: 'especial',
  },
  // Mais Crânio / Especial
  {
    id: 'c5',
    name: 'Sela Turca Towne / PF',
    category: 'cranio',
    positioning: 'Towne: AP Axial com 30º caudal. Perfil: Centralizado 2cm acima e à frente do MAE.',
    incidences: 'Towne e Perfil',
    angulation: 'Towne: 30 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Sela Turca centralizada.',
    structures: 'Sela turca, processos clinoides.',
    type: 'especial',
  },
  {
    id: 'c6',
    name: 'Órbita Mento / Rhese',
    category: 'cranio',
    positioning: 'Mento-naso (Waters) e Rhese (Oblíqua parietoorbital).',
    incidences: 'Waters e Rhese',
    angulation: 'Rhese: Canal óptico centrado.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Rhese mostra o canal óptico no quadrante externo inferior da órbita.',
    structures: 'Canais ópticos, assoalho orbital.',
    type: 'especial',
  }
];
