import { Exam, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cranio', name: 'Crânio', icon: 'Brain' },
  { id: 'coluna', name: 'Coluna', icon: 'PersonStanding' },
  { id: 'torax', name: 'Tórax', icon: 'Stethoscope' },
  { id: 'abdome', name: 'Abdome', icon: 'Activity' },
  { id: 'pelve', name: 'Pelve', icon: 'Disc' },
  { id: 'membros-superiores', name: 'Membros Superiores', icon: 'Hand' },
  { id: 'membros-inferiores', name: 'Membros Inferiores', icon: 'Footprints' },
  { id: 'pediatria', name: 'Pediatria (Infantil)', icon: 'Baby' },
  { id: 'kit-gripe', name: 'Kit Gripe', icon: 'Activity' },
  { id: 'densitometria', name: 'Densitometria Óssea', icon: 'Accessibility' },
];

export const INITIAL_EXAMS: Exam[] = [
  // Densitometria Óssea (DXA)
  {
    id: 'dxa1',
    name: 'DXA COLUNA LOMBAR (L1-L4)',
    category: 'densitometria',
    positioning: 'Decúbito dorsal, pernas elevadas em suporte (bloco) para retificar a lordose lombar e abrir os espaços intervertebrais.',
    incidences: 'AP',
    angulation: 'Perpendicular ao detector.',
    ffd: 'Fixa conforme fabricante.',
    kv: 'Baixa e Alta energia (Dual-energy).',
    mas: 'Ajuste automático.',
    observations: 'Remover metais e suspender cálcio 24h antes. Avalia densidade mineral óssea de L1 a L4. Critérios OMS: Normal (T ≥ -1), Osteopenia (-1 > T > -2.5), Osteoporose (T ≤ -2.5).',
    structures: 'Vértebras lombares (L1-L4).',
    type: 'rotina',
  },
  {
    id: 'dxa2',
    name: 'DXA FÊMUR PROXIMAL',
    category: 'densitometria',
    positioning: 'Decúbito dorsal, perna em rotação interna de 15-20º (usar posicionador) para melhor visualização do colo femoral.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: 'Fixa.',
    kv: 'Dual-energy.',
    mas: 'Automático.',
    observations: 'Análise do Colo Femoral e Fêmur Total. Evitar artefatos como próteses. T-score compara com adulto jovem; Z-score com mesma idade/etnia.',
    structures: 'Colo do fêmur, trocanter e triângulo de Ward.',
    type: 'rotina',
  },
  {
    id: 'dxa3',
    name: 'DXA ANTEBRAÇO (RÁDIO 33%)',
    category: 'densitometria',
    positioning: 'Paciente sentado ao lado do equipamento, antebraço apoiado horizontalmente. Geralmente o braço não dominante.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: 'Fixa.',
    kv: 'Dual-energy.',
    mas: 'Automático.',
    observations: 'Indicado quando coluna ou fêmur não podem ser avaliados (ex: próteses) ou em casos de hiperparatireoidismo.',
    structures: 'Rádio distal (33%).',
    type: 'especial',
  },
  // Abdome
  {
    id: 'a1',
    name: 'ABDOME',
    category: 'abdome',
    positioning: 'Paciente em decúbito dorsal.',
    incidences: 'AP em decúbito dorsal',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Alinhar com a crista ilíaca.',
    structures: 'Órgãos abdominais, psoas.',
    type: 'rotina',
  },
  {
    id: 'a2-torax',
    name: 'ABDOME AGUDO (TÓRAX PA)',
    category: 'abdome',
    positioning: 'Ortostase, tórax contra o bucky.',
    incidences: 'PA de tórax',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '110-120',
    mas: '2-5',
    observations: 'Pesquisar pneumoperitônio (ar sob o diafragma).',
    structures: 'Cúpulas diafragmáticas.',
    type: 'rotina',
  },
  {
    id: 'a2-decubito',
    name: 'ABDOME AGUDO (AP DECÚBITO)',
    category: 'abdome',
    positioning: 'Decúbito dorsal.',
    incidences: 'AP em decúbito dorsal',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Alinhar com a crista ilíaca.',
    structures: 'Alças intestinais, psoas.',
    type: 'rotina',
  },
  {
    id: 'a2-orto',
    name: 'ABDOME AGUDO (AP ORTOSTASE)',
    category: 'abdome',
    positioning: 'Ortostase.',
    incidences: 'AP em ortostase',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Verificar níveis hidroaéreos.',
    structures: 'Abdome total.',
    type: 'rotina',
  },
  // Membros Superiores
  {
    id: 'ms1-ap',
    name: 'ANTEBRAÇO AP',
    category: 'membros-superiores',
    positioning: 'Braço estendido, palma para cima, supinação total.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Incluir articulações do cotovelo e punho.',
    structures: 'Rádio e ulna em AP.',
    type: 'rotina',
  },
  {
    id: 'ms1-perfil',
    name: 'ANTEBRAÇO PERFIL',
    category: 'membros-superiores',
    positioning: 'Cotovelo fletido 90 graus, mão em perfil lateral.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Sobreposição distal de rádio e ulna.',
    structures: 'Rádio e ulna em perfil.',
    type: 'rotina',
  },
  {
    id: 'ms2-ap',
    name: 'CLAVÍCULA AP',
    category: 'membros-superiores',
    positioning: 'Paciente em ortostase ou decúbito, braços ao lado do corpo.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Suspensão de respiração.',
    structures: 'Clavícula por inteiro.',
    type: 'rotina',
  },
  {
    id: 'ms2-axial',
    name: 'CLAVÍCULA AXIAL',
    category: 'membros-superiores',
    positioning: 'Paciente em ortostase ou decúbito.',
    incidences: 'Axial',
    angulation: '15-30 graus cefálico.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Projeta a clavícula acima das costelas.',
    structures: 'Clavícula sem sobreposição.',
    type: 'rotina',
  },
  {
    id: 'ms3-ap',
    name: 'COTOVELO AP',
    category: 'membros-superiores',
    positioning: 'Braço totalmente estendido, supinado.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '5-10',
    observations: 'Visualizar espaço articular.',
    structures: 'Úmero distal e rádio/ulna proximais.',
    type: 'rotina',
  },
  {
    id: 'ms3-perfil',
    name: 'COTOVELO PERFIL',
    category: 'membros-superiores',
    positioning: 'Cotovelo fletido 90 graus, polegar para cima.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '5-10',
    observations: 'Olécrano em perfil.',
    structures: 'Articulação do cotovelo em perfil lateral.',
    type: 'rotina',
  },
  {
    id: 'ms4-pa',
    name: 'DEDOS PA (QD)',
    category: 'membros-superiores',
    positioning: 'Dedo estendido sobre o detector.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-4',
    observations: 'Incluir articulação metacarpofalângica.',
    structures: 'Falanges e articulações interfalângicas.',
    type: 'rotina',
  },
  {
    id: 'ms4-obliqua',
    name: 'DEDOS OBLÍQUA (QD)',
    category: 'membros-superiores',
    positioning: 'Dedo rodado 45 graus (usar cunha se necessário).',
    incidences: 'Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-4',
    observations: 'Isolar o dedo de interesse.',
    structures: 'Falanges em projeção oblíqua.',
    type: 'rotina',
  },
  {
    id: 'ms5-ap',
    name: 'ESCÁPULA AP',
    category: 'membros-superiores',
    positioning: 'Abduzir o braço 90º para liberar a escápula.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Respiração calma ou apneia.',
    structures: 'Corpo da escápula.',
    type: 'rotina',
  },
  {
    id: 'ms5-perfil',
    name: 'ESCÁPULA PERFIL',
    category: 'membros-superiores',
    positioning: 'Perfil escapular (Y), paciente rodado 45-60º.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Acrômio e processo coracoide visíveis.',
    structures: 'Escápula em perfil lateral.',
    type: 'rotina',
  },
  {
    id: 'ms6-pa',
    name: 'MÃO PA',
    category: 'membros-superiores',
    positioning: 'Mão espalmada, dedos levemente afastados.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-5',
    observations: 'Centralizar no 3º metacarpo.',
    structures: 'Carpo, metacarpos e falanges.',
    type: 'rotina',
  },
  {
    id: 'ms6-obliqua',
    name: 'MÃO OBLÍQUA',
    category: 'membros-superiores',
    positioning: 'Mão rodada 45 graus lateralmente.',
    incidences: 'Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-55',
    mas: '2-5',
    observations: 'Dedos em "leque" para evitar sobreposição.',
    structures: 'Ossos da mão em oblíqua.',
    type: 'rotina',
  },
  {
    id: 'ms7-ri',
    name: 'OMBRO AP (ROTAÇÃO INTERNA)',
    category: 'membros-superiores',
    positioning: 'Epicôndilos perpendiculares ao detector.',
    incidences: 'AP rotação interna',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-35',
    observations: 'Evidencia o tubérculo menor.',
    structures: 'Tubérculo menor em perfil.',
    type: 'rotina',
  },
  {
    id: 'ms7-re',
    name: 'OMBRO AP (ROTAÇÃO EXTERNA)',
    category: 'membros-superiores',
    positioning: 'Epicôndilos paralelos ao detector.',
    incidences: 'AP rotação externa',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-35',
    observations: 'Evidencia o tubérculo maior.',
    structures: 'Tubérculo maior em perfil lateral.',
    type: 'rotina',
  },
  {
    id: 'ms8-ap',
    name: 'OMBRO AP (NEUTRO)',
    category: 'membros-superiores',
    positioning: 'Posição anatômica do braço conforme tolerado.',
    incidences: 'AP neutro',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Para casos de trauma agudo.',
    structures: 'Articulação glenoumeral.',
    type: 'rotina',
  },
  {
    id: 'ms8-axilar',
    name: 'OMBRO PERFIL AXILAR',
    category: 'membros-superiores',
    positioning: 'Abdução do braço (se possível), raio através da axila.',
    incidences: 'Perfil axilar',
    angulation: '15-30 graus medial.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Avaliar relação cabeça umeral e glenoide.',
    structures: 'Cabeça do úmero e cavidade glenoide.',
    type: 'rotina',
  },
  {
    id: 'ms8-y',
    name: 'OMBRO PERFIL ESCAPULAR (Y)',
    category: 'membros-superiores',
    positioning: 'Paciente rodado 45-60º contra o bucky.',
    incidences: 'Perfil escapular',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Excelente para luxações.',
    structures: 'Úmero proximal sobreposto ao "Y" da escápula.',
    type: 'rotina',
  },
  {
    id: 'ms9-pa',
    name: 'PUNHO PA',
    category: 'membros-superiores',
    positioning: 'Mão espalmada, punho centralizado.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '3-6',
    observations: 'Abaixar o ombro para alinhar antebraço.',
    structures: 'Ossos do carpo, rádio e ulna distais.',
    type: 'rotina',
  },
  {
    id: 'ms9-perfil',
    name: 'PUNHO PERFIL',
    category: 'membros-superiores',
    positioning: 'Punho em lateral absoluto, polegar para cima.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '3-6',
    observations: 'Sobreposição de rádio e ulna distais.',
    structures: 'Carpais em perfil lateral.',
    type: 'rotina',
  },
  {
    id: 'ms10-ap',
    name: 'ÚMERO AP',
    category: 'membros-superiores',
    positioning: 'Braço em extensão, supinado.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Incluir articulações do ombro e cotovelo.',
    structures: 'Corpo do úmero.',
    type: 'rotina',
  },
  {
    id: 'ms10-lateral',
    name: 'ÚMERO PERFIL',
    category: 'membros-superiores',
    positioning: 'Cotovelo fletido, mão sobre o abdome.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Geralmente realizado em ortostase.',
    structures: 'Úmero em perfil lateral.',
    type: 'rotina',
  },
  {
    id: 'ms10-transtoracico',
    name: 'ÚMERO TRANSTORÁCICO',
    category: 'membros-superiores',
    positioning: 'Lado de interesse contra o detector, braço oposto elevado.',
    incidences: 'Transtorácico (Método Lawrence)',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-90',
    mas: '80-120',
    observations: 'Técnica de respiração longa.',
    structures: 'Úmero proximal através do tórax.',
    type: 'especial',
  },
  // Tórax
  {
    id: 't1',
    name: 'ARCOS COSTAIS',
    category: 'torax',
    positioning: 'Oblíqua anterior ou posterior conforme área de interesse.',
    incidences: 'Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '20-40',
    observations: 'Apneia em inspiração.',
    structures: 'Arcos costais.',
    type: 'rotina',
  },
  {
    id: 't1-ap',
    name: 'ARCOS COSTAIS AP',
    category: 'torax',
    positioning: 'Paciente em ortostase ou decúbito dorsal, braços ao longo do corpo.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '20-40',
    observations: 'Apneia em inspiração para arcos superiores, em expiração para arcos inferiores.',
    structures: 'Arcos costais (posteriores).',
    type: 'rotina',
  },
  {
    id: 't2-oad',
    name: 'ESTERNO OAD',
    category: 'torax',
    positioning: 'OAD: Paciente rodado 15-20 graus para a direita, esternoe centralizado no bucky.',
    incidences: 'OAD',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '30-50',
    observations: 'OAD projeta o esterno sobre a silhueta cardíaca.',
    structures: 'Manúbrio, corpo e processo xifoide.',
    type: 'rotina',
  },
  {
    id: 't2-perfil',
    name: 'ESTERNO PERFIL',
    category: 'torax',
    positioning: 'Perfil lateral, braços para trás para projetar o tórax.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '30-50',
    observations: 'Inspiração profunda.',
    structures: 'Esterno em perfil.',
    type: 'rotina',
  },
  {
    id: 't3-pa',
    name: 'TÓRAX PA (ADULTO)',
    category: 'torax',
    positioning: 'Ortostase, tórax contra o bucky, ombros para frente.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '110-120',
    mas: '2-5',
    observations: 'Inspiração profunda mantida.',
    structures: 'Pulmões, hilos, silhueta cardíaca.',
    type: 'rotina',
  },
  {
    id: 't3-perfil',
    name: 'TÓRAX PERFIL (ADULTO)',
    category: 'torax',
    positioning: 'Ortostase, perfil lateral contra o bucky, braços elevados.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '120-130',
    mas: '5-10',
    observations: 'Inspiração profunda.',
    structures: 'Campos pulmonares posterior e anterior.',
    type: 'rotina',
  },
  // Crânio & Face
  {
    id: 'c1-towne',
    name: 'ARCO ZIGOMÁTICO (TOWNE)',
    category: 'cranio',
    positioning: 'AP Axial (Towne).',
    incidences: 'Towne',
    angulation: '30-37 graus caudal.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '15-25',
    observations: 'Técnica fina para arcos zigomáticos.',
    structures: 'Arcos zigomáticos simétricos.',
    type: 'especial',
  },
  {
    id: 'c1-tangencial',
    name: 'ARCO ZIGOMÁTICO (TANGENCIAL)',
    category: 'cranio',
    positioning: 'Tangencial: Cabeça inclinada para o lado de interesse.',
    incidences: 'Tangencial',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '15-25',
    observations: 'Demonstra arqueamento do zigomático.',
    structures: 'Arco zigomático em projeção tangencial.',
    type: 'especial',
  },
  {
    id: 'c2-aberta',
    name: 'ATM BOCA ABERTA',
    category: 'cranio',
    positioning: 'Lateral com boca em abertura máxima.',
    incidences: 'Método Law (boca aberta)',
    angulation: '15 graus caudal.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-30',
    observations: 'Avaliar excursão condilar.',
    structures: 'Côndilo da mandíbula fora da fossa mandibular.',
    type: 'especial',
  },
  {
    id: 'c2-fechada',
    name: 'ATM BOCA FECHADA',
    category: 'cranio',
    positioning: 'Lateral com boca fechada.',
    incidences: 'Método Law (boca fechada)',
    angulation: '15 graus caudal.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-30',
    observations: 'Avaliar posição de repouso.',
    structures: 'Côndilo na fossa mandibular.',
    type: 'especial',
  },
  {
    id: 'c3-perfil',
    name: 'CAVUM PERFIL',
    category: 'cranio',
    positioning: 'Perfil de face com técnica de partes moles.',
    incidences: 'Perfil de face',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-10',
    observations: 'Visualizar adenoide.',
    structures: 'Coluna aérea da nasofaringe.',
    type: 'rotina',
  },
  {
    id: 'c4-towne',
    name: 'CRÂNIO TOWNE',
    category: 'cranio',
    positioning: 'AP Axial (Towne).',
    incidences: 'Towne',
    angulation: '30 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Visualizar osso occipital.',
    structures: 'Osso occipital, rochedo.',
    type: 'rotina',
  },
  {
    id: 'c4-pa',
    name: 'CRÂNIO PA',
    category: 'cranio',
    positioning: 'PA de Crânio, nariz e testa encostados.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Evitar rotação.',
    structures: 'Frontal, órbitas, seios.',
    type: 'rotina',
  },
  {
    id: 'c4-perfil',
    name: 'CRÂNIO PERFIL',
    category: 'cranio',
    positioning: 'Posição de nadador ou em ortostase lateral.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Sobrepor os ramos da mandíbula.',
    structures: 'Calota craniana em perfil.',
    type: 'rotina',
  },
  {
    id: 'c5-pa',
    name: 'MANDÍBULA PA',
    category: 'cranio',
    positioning: 'PA de mandíbula.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-35',
    observations: 'Avaliar simetria dos ramos.',
    structures: 'Corpo e ramos da mandíbula.',
    type: 'rotina',
  },
  {
    id: 'c5-bellot',
    name: 'MANDÍBULA BELLOT',
    category: 'cranio',
    positioning: 'Oblíqua axiolateral (Bellot).',
    incidences: 'Bellot (axiolateral)',
    angulation: '25-30 graus cefálico.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '20-35',
    observations: 'Visualizar ramo da mandíbula de interesse.',
    structures: 'Ramo mandibular sem sobreposição.',
    type: 'rotina',
  },
  {
    id: 'c7-pd',
    name: 'OSSOS NASAIS (PERFIL DIREITO)',
    category: 'cranio',
    positioning: 'Perfil lateral direito da face.',
    incidences: 'Perfil D',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Técnica de partes moles.',
    structures: 'Ossos nasais.',
    type: 'rotina',
  },
  {
    id: 'c7-pe',
    name: 'OSSOS NASAIS (PERFIL ESQUERDO)',
    category: 'cranio',
    positioning: 'Perfil lateral esquerdo da face.',
    incidences: 'Perfil E',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Técnica de partes moles.',
    structures: 'Ossos nasais.',
    type: 'rotina',
  },
  {
    id: 'c8-waters',
    name: 'ÓRBITA (WATERS)',
    category: 'cranio',
    positioning: 'Mento-naso (Waters).',
    incidences: 'Mento-naso',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Visualizar soalho das órbitas.',
    structures: 'Assoalho orbital.',
    type: 'especial',
  },
  {
    id: 'c8-rhese',
    name: 'ÓRBITA (RHESE)',
    category: 'cranio',
    positioning: 'Cabeça rodada 37 graus (método de Rhese).',
    incidences: 'Rhese',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '25-45',
    observations: 'Visualizar canal óptico.',
    structures: 'Canal óptico no quadrante ínfero-lateral.',
    type: 'especial',
  },
  {
    id: 'c10-towne',
    name: 'SELA TÚRCICA (TOWNE)',
    category: 'cranio',
    positioning: 'AP Axial (Towne).',
    incidences: 'Towne',
    angulation: '30 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Visualizar dorso da sela túrcica.',
    structures: 'Sela túrcica através do forame magno.',
    type: 'especial',
  },
  {
    id: 'c10-perfil',
    name: 'SELA TÚRCICA (PERFIL)',
    category: 'cranio',
    positioning: 'Perfil lateral absoluto.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '20-40',
    observations: 'Sela túrcica centralizada.',
    structures: 'Processos clinoides, fossa hipofisária.',
    type: 'especial',
  },
  // Coluna
  {
    id: 'col1-ap',
    name: 'COLUNA CERVICAL AP',
    category: 'coluna',
    positioning: 'AP axial, queixo elevado.',
    incidences: 'AP axial',
    angulation: 'AP: 15-20 graus cefálico.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Visualizar de C3 a C7.',
    structures: 'Vértebras cervicais inferiores.',
    type: 'rotina',
  },
  {
    id: 'col1-perfil',
    name: 'COLUNA CERVICAL PERFIL',
    category: 'coluna',
    positioning: 'Perfil verdadeiro, ombros para baixo.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '150-180 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Avaliar alinhamento vertebral.',
    structures: 'C1 a C7 em perfil.',
    type: 'rotina',
  },
  {
    id: 'col2-ap',
    name: 'COLUNA TORÁCICA AP',
    category: 'coluna',
    positioning: 'Decúbito dorsal ou ortostase.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Alinhar com T7.',
    structures: 'Vértebras torácicas simétricas.',
    type: 'rotina',
  },
  {
    id: 'col2-perfil',
    name: 'COLUNA TORÁCICA PERFIL',
    category: 'coluna',
    positioning: 'Perfil lateral em decúbito ou ortostase.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Técnica de respiração (exposição longa) para apagar costelas.',
    structures: 'Corpos vertebrais e espaços discais.',
    type: 'rotina',
  },
  {
    id: 'col3-ap',
    name: 'COLUNA LOMBAR AP',
    category: 'coluna',
    positioning: 'Decúbito dorsal, fletir joelhos para retificar lordose.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-95',
    mas: '60-120',
    observations: 'Alinhar com L3.',
    structures: 'L1 a L5.',
    type: 'rotina',
  },
  {
    id: 'col3-perfil',
    name: 'COLUNA LOMBAR PERFIL',
    category: 'coluna',
    positioning: 'Perfil lateral, joelhos fletidos para estabilidade.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-95',
    mas: '80-150',
    observations: 'Visualizar forames intervertebrais.',
    structures: 'L1 a L5 em perfil.',
    type: 'rotina',
  },
  {
    id: 'col4-sacro',
    name: 'SACRO AP AXIAL',
    category: 'coluna',
    positioning: 'Decúbito dorsal.',
    incidences: 'AP axial',
    angulation: '15º cefálico.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-50',
    observations: 'Esvaziar bexiga.',
    structures: 'Sacro sem sobreposição da sínfise púbica.',
    type: 'rotina',
  },
  {
    id: 'col4-coccyx',
    name: 'CÓCCIX AP AXIAL',
    category: 'coluna',
    positioning: 'Decúbito dorsal.',
    incidences: 'AP axial',
    angulation: '10º caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-50',
    observations: 'Esvaziar bexiga.',
    structures: 'Cóccix centrado.',
    type: 'rotina',
  },
  {
    id: 'col4-sacro-perfil',
    name: 'SACRO PERFIL',
    category: 'coluna',
    positioning: 'Perfil lateral em decúbito lateral absoluto.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-95',
    mas: '40-80',
    observations: 'Visualizar as articulações lombossacras.',
    structures: 'Sacro em projeção lateral.',
    type: 'rotina',
  },
  {
    id: 'col4-coccyx-perfil',
    name: 'CÓCCIX PERFIL',
    category: 'coluna',
    positioning: 'Perfil lateral focado no cóccix.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '80-95',
    mas: '40-80',
    observations: 'Visualizar o cóccix por inteiro.',
    structures: 'Cóccix em projeção lateral.',
    type: 'rotina',
  },
  // Pelve
  {
    id: 'p1',
    name: 'BACIA AP',
    category: 'pelve',
    positioning: 'Decúbito dorsal, pés em rotação interna de 15-20º para evidenciar os colos femorais.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Alinhar Plano Sagital Mediano com o centro da mesa.',
    structures: 'Pelve, quadris e colos femorais.',
    type: 'rotina',
  },
  {
    id: 'p2',
    name: 'BACIA POSIÇÃO DE RÃ',
    category: 'pelve',
    positioning: 'Paciente em decúbito dorsal, joelhos fletidos e coxas abduzidas (Método de Cleaves).',
    incidences: 'Posição de rã (Cleaves)',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '40-80',
    observations: 'Útil para comparar articulações coxofemorais simetricamente.',
    structures: 'Articulações coxofemorais e colos femorais em perfil lateral.',
    type: 'rotina',
  },
  // Membros Inferiores
  {
    id: 'mi1-axial',
    name: 'CALCÂNEO AXIAL',
    category: 'membros-inferiores',
    positioning: 'Axial de calcâneo (Planto-axial).',
    incidences: 'Axial',
    angulation: '40 graus cefálico.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '10-20',
    observations: 'Dorsoflexão máxima.',
    structures: 'Calcâneo alongado.',
    type: 'rotina',
  },
  {
    id: 'mi1-perfil',
    name: 'CALCÂNEO PERFIL',
    category: 'membros-inferiores',
    positioning: 'Perfil lateral do calcâneo.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-12',
    observations: 'Visualizar articulação subtalar.',
    structures: 'Calcâneo em perfil.',
    type: 'rotina',
  },
  {
    id: 'mi2-ap',
    name: 'DEDOS AP (PD)',
    category: 'membros-inferiores',
    positioning: 'AP dos artelhos.',
    incidences: 'AP',
    angulation: '10-15 graus cefálico.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Incluir articulação metatarsofalângica.',
    structures: 'Falanges do pé.',
    type: 'rotina',
  },
  {
    id: 'mi2-obliqua',
    name: 'DEDOS OBLÍQUA (PD)',
    category: 'membros-inferiores',
    positioning: 'Oblíqua medial dos artelhos.',
    incidences: 'Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '2-4',
    observations: 'Isolar o artelho de interesse.',
    structures: 'Articulações interfalângicas sem sobreposição.',
    type: 'rotina',
  },
  {
    id: 'mi3-ap',
    name: 'FÊMUR DISTAL AP',
    category: 'membros-inferiores',
    positioning: 'AP focado no joelho/fêmur distal.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Incluir articulação do joelho.',
    structures: 'Fêmur distal e joelho.',
    type: 'rotina',
  },
  {
    id: 'mi3-perfil',
    name: 'FÊMUR DISTAL PERFIL',
    category: 'membros-inferiores',
    positioning: 'Perfil focado no joelho/fêmur distal.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '70-80',
    mas: '15-30',
    observations: 'Perfil lateral.',
    structures: 'Fêmur distal em perfil.',
    type: 'rotina',
  },
  {
    id: 'mi4',
    name: 'FÊMUR PROXIMAL',
    category: 'membros-inferiores',
    positioning: 'AP de quadril/fêmur proximal.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-60',
    observations: 'Incluir articulação coxofemoral.',
    structures: 'Fêmur proximal.',
    type: 'rotina',
  },
  {
    id: 'mi5',
    name: 'FOSSA INTERCONDILAR',
    category: 'membros-inferiores',
    positioning: 'Método de Túnel: PA ou AP com joelho fletido.',
    incidences: 'PA (método de túnel)',
    angulation: '40-45 graus caudal.',
    ffd: '100 cm',
    kv: '65-75',
    mas: '10-20',
    observations: 'Visualizar eminência intercondilar.',
    structures: 'Fossa intercondilar.',
    type: 'especial',
  },
  {
    id: 'mi6-ap',
    name: 'JOELHO AP',
    category: 'membros-inferiores',
    positioning: 'AP em decúbito ou ortostase.',
    incidences: 'AP',
    angulation: '5-7 graus cefálico.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Carga se solicitada.',
    structures: 'Joelho simétrico.',
    type: 'rotina',
  },
  {
    id: 'mi6-perfil',
    name: 'JOELHO PERFIL',
    category: 'membros-inferiores',
    positioning: 'Perfil lateral fletido 20-30 graus.',
    incidences: 'Perfil',
    angulation: '5-7 graus cefálico.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Sobrepor côndilos femorais.',
    structures: 'Espaço femoropatelar e femorotibial.',
    type: 'rotina',
  },
  {
    id: 'mi7-tangencial',
    name: 'PATELA TANGENCIAL',
    category: 'membros-inferiores',
    positioning: 'Tangencial (Método de Settegast).',
    incidences: 'Tangencial',
    angulation: '15-20 graus.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-12',
    observations: 'Cuidado ao fletir joelho em trauma.',
    structures: 'Espaço patelofemoral.',
    type: 'rotina',
  },
  {
    id: 'mi7-perfil',
    name: 'PATELA PERFIL',
    category: 'membros-inferiores',
    positioning: 'Perfil verdadeiro de patela.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '5-12',
    observations: 'Evitar sobreposição com fêmur.',
    structures: 'Patela em perfil.',
    type: 'rotina',
  },
  {
    id: 'mi8-ap',
    name: 'PÉ AP',
    category: 'membros-inferiores',
    positioning: 'AP com 10º de inclinação cefálica.',
    incidences: 'AP',
    angulation: '10 graus cefálico.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Carga se necessário.',
    structures: 'Metatarsos e falanges.',
    type: 'rotina',
  },
  {
    id: 'mi8-obliqua',
    name: 'PÉ OBLÍQUA',
    category: 'membros-inferiores',
    positioning: 'Oblíqua medial (membro rodado 30 graus).',
    incidences: 'Oblíqua',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '4-8',
    observations: 'Visualiza cubóide.',
    structures: 'Ossos do tarso sem sobreposição.',
    type: 'rotina',
  },
  {
    id: 'mi9-ap',
    name: 'PERNA AP',
    category: 'membros-inferiores',
    positioning: 'AP de tíbia e fíbula.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Incluir joelho e tornozelo.',
    structures: 'Tíbia e fíbula.',
    type: 'rotina',
  },
  {
    id: 'mi9-perfil',
    name: 'PERNA PERFIL',
    category: 'membros-inferiores',
    positioning: 'Perfil lateral de tíbia e fíbula.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '60-70',
    mas: '8-15',
    observations: 'Tornozelo em perfil lateral.',
    structures: 'Perna em perfil.',
    type: 'rotina',
  },
  {
    id: 'mi10',
    name: 'SESAMOIDE',
    category: 'membros-inferiores',
    positioning: 'Tangencial de Lewis: Pé em hiperextensão.',
    incidences: 'Tangencial (Lewis)',
    angulation: 'Perpendicular ao detector.',
    ffd: '100 cm',
    kv: '50-60',
    mas: '3-6',
    observations: 'Puxar os dedos com fita.',
    structures: 'Ossos sesamoides do hálux.',
    type: 'especial',
  },
  {
    id: 'mi11-ap',
    name: 'TORNOZELO AP',
    category: 'membros-inferiores',
    positioning: 'AP, pé em 90 graus.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '5-12',
    observations: 'Simétrico.',
    structures: 'Maleólos e tálus.',
    type: 'rotina',
  },
  {
    id: 'mi11-perfil',
    name: 'TORNOZELO PERFIL',
    category: 'membros-inferiores',
    positioning: 'Perfil lateral do tornozelo.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100 cm',
    kv: '55-65',
    mas: '5-12',
    observations: 'Visualizar base do 5º metatarso.',
    structures: 'Articulação do tornozelo em perfil.',
    type: 'rotina',
  },
  // Pediatria
  {
    id: 'ped1-ap',
    name: 'TÓRAX PEDIÁTRICO AP',
    category: 'pediatria',
    positioning: 'AP em decúbito ou ortostase imobilizado.',
    incidences: 'AP',
    angulation: 'Perpendicular.',
    ffd: '100-150 cm',
    kv: '55-65',
    mas: '1.5-4',
    observations: 'Exposição rápida, realizada na inspiração.',
    structures: 'Campos pulmonares pediátricos.',
    type: 'rotina',
  },
  {
    id: 'ped1-perfil',
    name: 'TÓRAX PEDIÁTRICO PERFIL',
    category: 'pediatria',
    positioning: 'Perfil lateral imobilizado.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '100-150 cm',
    kv: '55-65',
    mas: '1.5-4',
    observations: 'Braços elevados.',
    structures: 'Campos pulmonares em perfil.',
    type: 'rotina',
  },
  // Kit Gripe
  {
    id: 'kg1',
    name: 'MENTO-NASO (Kit Gripe)',
    category: 'kit-gripe',
    positioning: 'Mento-naso (Waters).',
    incidences: 'Mento-naso',
    angulation: 'Perpendicular ao receptor.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-45',
    observations: 'Mento encostado no receptor, boca aberta se possível.',
    structures: 'Seios maxilares.',
    type: 'rotina',
  },
  {
    id: 'kg2',
    name: 'FRONTO-NASO (Kit Gripe)',
    category: 'kit-gripe',
    positioning: 'Fronto-naso (Caldwell).',
    incidences: 'Fronto-naso',
    angulation: '15 graus caudal.',
    ffd: '100 cm',
    kv: '75-85',
    mas: '30-45',
    observations: 'Nariz e testa encostados no receptor.',
    structures: 'Seios frontais e etmoidais.',
    type: 'rotina',
  },
  {
    id: 'kg3',
    name: 'TÓRAX PA (Kit Gripe)',
    category: 'kit-gripe',
    positioning: 'Ortostase, tórax contra o bucky.',
    incidences: 'PA',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '110-120',
    mas: '2-5',
    observations: 'Inspiração profunda mantida.',
    structures: 'Pulmões, silhueta cardíaca.',
    type: 'rotina',
  },
  {
    id: 'kg4',
    name: 'TÓRAX PERFIL (Kit Gripe)',
    category: 'kit-gripe',
    positioning: 'Ortostase, perfil lateral contra o bucky.',
    incidences: 'Perfil',
    angulation: 'Perpendicular.',
    ffd: '180 cm',
    kv: '120-130',
    mas: '5-10',
    observations: 'Braços elevados.',
    structures: 'Campos pulmonares em perfil.',
    type: 'rotina',
  },
];

